// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: go/net/grpc/example/data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proto name 默认为变量名，proto json默认为小驼峰模式, json默认为变量名
	// [json_name = "RequestId"]将指定proto json的标签, 此时需要设置
	// protojson编解码器选项UseProtoNames为false
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"` // 请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowRequest) Reset() {
	*x = NowRequest{}
	mi := &file_go_net_grpc_example_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowRequest) ProtoMessage() {}

func (x *NowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_net_grpc_example_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowRequest.ProtoReflect.Descriptor instead.
func (*NowRequest) Descriptor() ([]byte, []int) {
	return file_go_net_grpc_example_data_proto_rawDescGZIP(), []int{0}
}

func (x *NowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"` // 请求ID
	Date          string                 `protobuf:"bytes,2,opt,name=date,json=Date,proto3" json:"date,omitempty"`                  // 当前时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowResponse) Reset() {
	*x = NowResponse{}
	mi := &file_go_net_grpc_example_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowResponse) ProtoMessage() {}

func (x *NowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_net_grpc_example_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowResponse.ProtoReflect.Descriptor instead.
func (*NowResponse) Descriptor() ([]byte, []int) {
	return file_go_net_grpc_example_data_proto_rawDescGZIP(), []int{1}
}

func (x *NowResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NowResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type NowErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"` // 请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowErrorRequest) Reset() {
	*x = NowErrorRequest{}
	mi := &file_go_net_grpc_example_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowErrorRequest) ProtoMessage() {}

func (x *NowErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_net_grpc_example_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowErrorRequest.ProtoReflect.Descriptor instead.
func (*NowErrorRequest) Descriptor() ([]byte, []int) {
	return file_go_net_grpc_example_data_proto_rawDescGZIP(), []int{2}
}

func (x *NowErrorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NowErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"` // 请求ID
	Date          string                 `protobuf:"bytes,2,opt,name=date,json=Date,proto3" json:"date,omitempty"`                  // 当前时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowErrorResponse) Reset() {
	*x = NowErrorResponse{}
	mi := &file_go_net_grpc_example_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowErrorResponse) ProtoMessage() {}

func (x *NowErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_net_grpc_example_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowErrorResponse.ProtoReflect.Descriptor instead.
func (*NowErrorResponse) Descriptor() ([]byte, []int) {
	return file_go_net_grpc_example_data_proto_rawDescGZIP(), []int{3}
}

func (x *NowErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NowErrorResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_go_net_grpc_example_data_proto protoreflect.FileDescriptor

const file_go_net_grpc_example_data_proto_rawDesc = "" +
	"\n" +
	"\x1ego/net/grpc/example/data.proto\x12\x0fsea.api.seadate\x1a google/protobuf/descriptor.proto\"+\n" +
	"\n" +
	"NowRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\"@\n" +
	"\vNowResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04Date\"0\n" +
	"\x0fNowErrorRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\"E\n" +
	"\x10NowErrorResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04Date2\xa7\x01\n" +
	"\x0eSeaDateService\x12B\n" +
	"\x03Now\x12\x1b.sea.api.seadate.NowRequest\x1a\x1c.sea.api.seadate.NowResponse\"\x00\x12Q\n" +
	"\bNowError\x12 .sea.api.seadate.NowErrorRequest\x1a!.sea.api.seadate.NowErrorResponse\"\x00B7Z5github.com/kaydxh/sea/api/protoapi-spec/seadate/v1;v1b\x06proto3"

var (
	file_go_net_grpc_example_data_proto_rawDescOnce sync.Once
	file_go_net_grpc_example_data_proto_rawDescData []byte
)

func file_go_net_grpc_example_data_proto_rawDescGZIP() []byte {
	file_go_net_grpc_example_data_proto_rawDescOnce.Do(func() {
		file_go_net_grpc_example_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_net_grpc_example_data_proto_rawDesc), len(file_go_net_grpc_example_data_proto_rawDesc)))
	})
	return file_go_net_grpc_example_data_proto_rawDescData
}

var file_go_net_grpc_example_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_net_grpc_example_data_proto_goTypes = []any{
	(*NowRequest)(nil),       // 0: sea.api.seadate.NowRequest
	(*NowResponse)(nil),      // 1: sea.api.seadate.NowResponse
	(*NowErrorRequest)(nil),  // 2: sea.api.seadate.NowErrorRequest
	(*NowErrorResponse)(nil), // 3: sea.api.seadate.NowErrorResponse
}
var file_go_net_grpc_example_data_proto_depIdxs = []int32{
	0, // 0: sea.api.seadate.SeaDateService.Now:input_type -> sea.api.seadate.NowRequest
	2, // 1: sea.api.seadate.SeaDateService.NowError:input_type -> sea.api.seadate.NowErrorRequest
	1, // 2: sea.api.seadate.SeaDateService.Now:output_type -> sea.api.seadate.NowResponse
	3, // 3: sea.api.seadate.SeaDateService.NowError:output_type -> sea.api.seadate.NowErrorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_net_grpc_example_data_proto_init() }
func file_go_net_grpc_example_data_proto_init() {
	if File_go_net_grpc_example_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_net_grpc_example_data_proto_rawDesc), len(file_go_net_grpc_example_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_net_grpc_example_data_proto_goTypes,
		DependencyIndexes: file_go_net_grpc_example_data_proto_depIdxs,
		MessageInfos:      file_go_net_grpc_example_data_proto_msgTypes,
	}.Build()
	File_go_net_grpc_example_data_proto = out.File
	file_go_net_grpc_example_data_proto_goTypes = nil
	file_go_net_grpc_example_data_proto_depIdxs = nil
}
