// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/openapi-spec/types/sdk-go.types.proto

#ifndef PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto
#define PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "api/openapi-spec/types/code/sdk-go.code.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto 

namespace protobuf_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto
namespace sdk {
namespace api {
namespace types {
}  // namespace types
}  // namespace api
}  // namespace sdk
namespace sdk {
namespace api {
namespace types {

// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace types
}  // namespace api
}  // namespace sdk

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2ftypes_2fsdk_2dgo_2etypes_2eproto
