// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gocv/gocv.magick.proto

package gocv

import (
	code "github.com/kaydxh/golang/pkg/gocv/cgo/api/openapi-spec/types/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MagickInitializeMagickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *MagickInitializeMagickRequest) Reset() {
	*x = MagickInitializeMagickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocv_gocv_magick_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagickInitializeMagickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagickInitializeMagickRequest) ProtoMessage() {}

func (x *MagickInitializeMagickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gocv_gocv_magick_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagickInitializeMagickRequest.ProtoReflect.Descriptor instead.
func (*MagickInitializeMagickRequest) Descriptor() ([]byte, []int) {
	return file_gocv_gocv_magick_proto_rawDescGZIP(), []int{0}
}

func (x *MagickInitializeMagickRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MagickInitializeMagickResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *code.CgoError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MagickInitializeMagickResponse) Reset() {
	*x = MagickInitializeMagickResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gocv_gocv_magick_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagickInitializeMagickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagickInitializeMagickResponse) ProtoMessage() {}

func (x *MagickInitializeMagickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gocv_gocv_magick_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagickInitializeMagickResponse.ProtoReflect.Descriptor instead.
func (*MagickInitializeMagickResponse) Descriptor() ([]byte, []int) {
	return file_gocv_gocv_magick_proto_rawDescGZIP(), []int{1}
}

func (x *MagickInitializeMagickResponse) GetError() *code.CgoError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_gocv_gocv_magick_proto protoreflect.FileDescriptor

var file_gocv_gocv_magick_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6f, 0x63, 0x76, 0x2f, 0x67, 0x6f, 0x63, 0x76, 0x2e, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x64, 0x6b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x6f, 0x63, 0x76, 0x1a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63,
	0x6f, 0x64, 0x65, 0x2f, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x1d, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x6b, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x50, 0x0a, 0x1e, 0x4d, 0x61,
	0x67, 0x69, 0x63, 0x6b, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x4d, 0x61,
	0x67, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x67, 0x6f,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x79, 0x64, 0x78,
	0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x63,
	0x76, 0x2f, 0x63, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70,
	0x69, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x67, 0x6f, 0x63, 0x76, 0x3b, 0x67, 0x6f, 0x63, 0x76,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gocv_gocv_magick_proto_rawDescOnce sync.Once
	file_gocv_gocv_magick_proto_rawDescData = file_gocv_gocv_magick_proto_rawDesc
)

func file_gocv_gocv_magick_proto_rawDescGZIP() []byte {
	file_gocv_gocv_magick_proto_rawDescOnce.Do(func() {
		file_gocv_gocv_magick_proto_rawDescData = protoimpl.X.CompressGZIP(file_gocv_gocv_magick_proto_rawDescData)
	})
	return file_gocv_gocv_magick_proto_rawDescData
}

var file_gocv_gocv_magick_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gocv_gocv_magick_proto_goTypes = []interface{}{
	(*MagickInitializeMagickRequest)(nil),  // 0: sdk.api.gocv.MagickInitializeMagickRequest
	(*MagickInitializeMagickResponse)(nil), // 1: sdk.api.gocv.MagickInitializeMagickResponse
	(*code.CgoError)(nil),                  // 2: sdk.types.code.CgoError
}
var file_gocv_gocv_magick_proto_depIdxs = []int32{
	2, // 0: sdk.api.gocv.MagickInitializeMagickResponse.error:type_name -> sdk.types.code.CgoError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gocv_gocv_magick_proto_init() }
func file_gocv_gocv_magick_proto_init() {
	if File_gocv_gocv_magick_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gocv_gocv_magick_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagickInitializeMagickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gocv_gocv_magick_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagickInitializeMagickResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gocv_gocv_magick_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gocv_gocv_magick_proto_goTypes,
		DependencyIndexes: file_gocv_gocv_magick_proto_depIdxs,
		MessageInfos:      file_gocv_gocv_magick_proto_msgTypes,
	}.Build()
	File_gocv_gocv_magick_proto = out.File
	file_gocv_gocv_magick_proto_rawDesc = nil
	file_gocv_gocv_magick_proto_goTypes = nil
	file_gocv_gocv_magick_proto_depIdxs = nil
}
