// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/openapi-spec/gocv/gocv.magick.proto

#ifndef PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto
#define PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "api/openapi-spec/types/code/sdk-go.code.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto 

namespace protobuf_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto
namespace sdk {
namespace api {
namespace gocv {
class MagickInitializeMagickRequest;
class MagickInitializeMagickRequestDefaultTypeInternal;
extern MagickInitializeMagickRequestDefaultTypeInternal _MagickInitializeMagickRequest_default_instance_;
class MagickInitializeMagickResponse;
class MagickInitializeMagickResponseDefaultTypeInternal;
extern MagickInitializeMagickResponseDefaultTypeInternal _MagickInitializeMagickResponse_default_instance_;
}  // namespace gocv
}  // namespace api
}  // namespace sdk
namespace google {
namespace protobuf {
template<> ::sdk::api::gocv::MagickInitializeMagickRequest* Arena::CreateMaybeMessage<::sdk::api::gocv::MagickInitializeMagickRequest>(Arena*);
template<> ::sdk::api::gocv::MagickInitializeMagickResponse* Arena::CreateMaybeMessage<::sdk::api::gocv::MagickInitializeMagickResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace sdk {
namespace api {
namespace gocv {

// ===================================================================

class MagickInitializeMagickRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sdk.api.gocv.MagickInitializeMagickRequest) */ {
 public:
  MagickInitializeMagickRequest();
  virtual ~MagickInitializeMagickRequest();

  MagickInitializeMagickRequest(const MagickInitializeMagickRequest& from);

  inline MagickInitializeMagickRequest& operator=(const MagickInitializeMagickRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MagickInitializeMagickRequest(MagickInitializeMagickRequest&& from) noexcept
    : MagickInitializeMagickRequest() {
    *this = ::std::move(from);
  }

  inline MagickInitializeMagickRequest& operator=(MagickInitializeMagickRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MagickInitializeMagickRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MagickInitializeMagickRequest* internal_default_instance() {
    return reinterpret_cast<const MagickInitializeMagickRequest*>(
               &_MagickInitializeMagickRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MagickInitializeMagickRequest* other);
  friend void swap(MagickInitializeMagickRequest& a, MagickInitializeMagickRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MagickInitializeMagickRequest* New() const final {
    return CreateMaybeMessage<MagickInitializeMagickRequest>(NULL);
  }

  MagickInitializeMagickRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MagickInitializeMagickRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MagickInitializeMagickRequest& from);
  void MergeFrom(const MagickInitializeMagickRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MagickInitializeMagickRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string path = 1;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  #if LANG_CXX11
  void set_path(::std::string&& value);
  #endif
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:sdk.api.gocv.MagickInitializeMagickRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MagickInitializeMagickResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sdk.api.gocv.MagickInitializeMagickResponse) */ {
 public:
  MagickInitializeMagickResponse();
  virtual ~MagickInitializeMagickResponse();

  MagickInitializeMagickResponse(const MagickInitializeMagickResponse& from);

  inline MagickInitializeMagickResponse& operator=(const MagickInitializeMagickResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MagickInitializeMagickResponse(MagickInitializeMagickResponse&& from) noexcept
    : MagickInitializeMagickResponse() {
    *this = ::std::move(from);
  }

  inline MagickInitializeMagickResponse& operator=(MagickInitializeMagickResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MagickInitializeMagickResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MagickInitializeMagickResponse* internal_default_instance() {
    return reinterpret_cast<const MagickInitializeMagickResponse*>(
               &_MagickInitializeMagickResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MagickInitializeMagickResponse* other);
  friend void swap(MagickInitializeMagickResponse& a, MagickInitializeMagickResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MagickInitializeMagickResponse* New() const final {
    return CreateMaybeMessage<MagickInitializeMagickResponse>(NULL);
  }

  MagickInitializeMagickResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MagickInitializeMagickResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MagickInitializeMagickResponse& from);
  void MergeFrom(const MagickInitializeMagickResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MagickInitializeMagickResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .sdk.types.code.CgoError error = 1;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  private:
  const ::sdk::types::code::CgoError& _internal_error() const;
  public:
  const ::sdk::types::code::CgoError& error() const;
  ::sdk::types::code::CgoError* release_error();
  ::sdk::types::code::CgoError* mutable_error();
  void set_allocated_error(::sdk::types::code::CgoError* error);

  // @@protoc_insertion_point(class_scope:sdk.api.gocv.MagickInitializeMagickResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::sdk::types::code::CgoError* error_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MagickInitializeMagickRequest

// string path = 1;
inline void MagickInitializeMagickRequest::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MagickInitializeMagickRequest::path() const {
  // @@protoc_insertion_point(field_get:sdk.api.gocv.MagickInitializeMagickRequest.path)
  return path_.GetNoArena();
}
inline void MagickInitializeMagickRequest::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sdk.api.gocv.MagickInitializeMagickRequest.path)
}
#if LANG_CXX11
inline void MagickInitializeMagickRequest::set_path(::std::string&& value) {
  
  path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sdk.api.gocv.MagickInitializeMagickRequest.path)
}
#endif
inline void MagickInitializeMagickRequest::set_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sdk.api.gocv.MagickInitializeMagickRequest.path)
}
inline void MagickInitializeMagickRequest::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sdk.api.gocv.MagickInitializeMagickRequest.path)
}
inline ::std::string* MagickInitializeMagickRequest::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:sdk.api.gocv.MagickInitializeMagickRequest.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MagickInitializeMagickRequest::release_path() {
  // @@protoc_insertion_point(field_release:sdk.api.gocv.MagickInitializeMagickRequest.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MagickInitializeMagickRequest::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:sdk.api.gocv.MagickInitializeMagickRequest.path)
}

// -------------------------------------------------------------------

// MagickInitializeMagickResponse

// .sdk.types.code.CgoError error = 1;
inline bool MagickInitializeMagickResponse::has_error() const {
  return this != internal_default_instance() && error_ != NULL;
}
inline const ::sdk::types::code::CgoError& MagickInitializeMagickResponse::_internal_error() const {
  return *error_;
}
inline const ::sdk::types::code::CgoError& MagickInitializeMagickResponse::error() const {
  const ::sdk::types::code::CgoError* p = error_;
  // @@protoc_insertion_point(field_get:sdk.api.gocv.MagickInitializeMagickResponse.error)
  return p != NULL ? *p : *reinterpret_cast<const ::sdk::types::code::CgoError*>(
      &::sdk::types::code::_CgoError_default_instance_);
}
inline ::sdk::types::code::CgoError* MagickInitializeMagickResponse::release_error() {
  // @@protoc_insertion_point(field_release:sdk.api.gocv.MagickInitializeMagickResponse.error)
  
  ::sdk::types::code::CgoError* temp = error_;
  error_ = NULL;
  return temp;
}
inline ::sdk::types::code::CgoError* MagickInitializeMagickResponse::mutable_error() {
  
  if (error_ == NULL) {
    auto* p = CreateMaybeMessage<::sdk::types::code::CgoError>(GetArenaNoVirtual());
    error_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sdk.api.gocv.MagickInitializeMagickResponse.error)
  return error_;
}
inline void MagickInitializeMagickResponse::set_allocated_error(::sdk::types::code::CgoError* error) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(error_);
  }
  if (error) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:sdk.api.gocv.MagickInitializeMagickResponse.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gocv
}  // namespace api
}  // namespace sdk

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_api_2fopenapi_2dspec_2fgocv_2fgocv_2emagick_2eproto
