// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: pkg/webserver/webserver.proto

package webserver

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Web_Http_ApiFormatter int32

const (
	Web_Http_api_noop        Web_Http_ApiFormatter = 0
	Web_Http_tcloud_api_v30  Web_Http_ApiFormatter = 1
	Web_Http_trivial_api_v10 Web_Http_ApiFormatter = 2
	Web_Http_trivial_api_v20 Web_Http_ApiFormatter = 3
)

// Enum value maps for Web_Http_ApiFormatter.
var (
	Web_Http_ApiFormatter_name = map[int32]string{
		0: "api_noop",
		1: "tcloud_api_v30",
		2: "trivial_api_v10",
		3: "trivial_api_v20",
	}
	Web_Http_ApiFormatter_value = map[string]int32{
		"api_noop":        0,
		"tcloud_api_v30":  1,
		"trivial_api_v10": 2,
		"trivial_api_v20": 3,
	}
)

func (x Web_Http_ApiFormatter) Enum() *Web_Http_ApiFormatter {
	p := new(Web_Http_ApiFormatter)
	*p = x
	return p
}

func (x Web_Http_ApiFormatter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Web_Http_ApiFormatter) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_webserver_webserver_proto_enumTypes[0].Descriptor()
}

func (Web_Http_ApiFormatter) Type() protoreflect.EnumType {
	return &file_pkg_webserver_webserver_proto_enumTypes[0]
}

func (x Web_Http_ApiFormatter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Web_Http_ApiFormatter.Descriptor instead.
func (Web_Http_ApiFormatter) EnumDescriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Web struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BindAddress *Web_Net     `protobuf:"bytes,1,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	Grpc        *Web_Grpc    `protobuf:"bytes,3,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Http        *Web_Http    `protobuf:"bytes,4,opt,name=http,proto3" json:"http,omitempty"`
	Debug       *Web_Debug   `protobuf:"bytes,10,opt,name=debug,proto3" json:"debug,omitempty"`
	Monitor     *Web_Monitor `protobuf:"bytes,11,opt,name=monitor,proto3" json:"monitor,omitempty"`
}

func (x *Web) Reset() {
	*x = Web{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web) ProtoMessage() {}

func (x *Web) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web.ProtoReflect.Descriptor instead.
func (*Web) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0}
}

func (x *Web) GetBindAddress() *Web_Net {
	if x != nil {
		return x.BindAddress
	}
	return nil
}

func (x *Web) GetGrpc() *Web_Grpc {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Web) GetHttp() *Web_Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Web) GetDebug() *Web_Debug {
	if x != nil {
		return x.Debug
	}
	return nil
}

func (x *Web) GetMonitor() *Web_Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

type Web_Net struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Web_Net) Reset() {
	*x = Web_Net{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Net) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Net) ProtoMessage() {}

func (x *Web_Net) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Net.ProtoReflect.Descriptor instead.
func (*Web_Net) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Web_Net) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Web_Net) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Web_Grpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxConcurrencyUnary   int32              `protobuf:"varint,1,opt,name=max_concurrency_unary,json=maxConcurrencyUnary,proto3" json:"max_concurrency_unary,omitempty"`
	MaxConcurrencyStream  int32              `protobuf:"varint,2,opt,name=max_concurrency_stream,json=maxConcurrencyStream,proto3" json:"max_concurrency_stream,omitempty"`
	MaxReceiveMessageSize int32              `protobuf:"varint,3,opt,name=max_receive_message_size,json=maxReceiveMessageSize,proto3" json:"max_receive_message_size,omitempty"`
	MaxSendMessageSize    int32              `protobuf:"varint,4,opt,name=max_send_message_size,json=maxSendMessageSize,proto3" json:"max_send_message_size,omitempty"`
	Timeout               *duration.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *Web_Grpc) Reset() {
	*x = Web_Grpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Grpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Grpc) ProtoMessage() {}

func (x *Web_Grpc) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Grpc.ProtoReflect.Descriptor instead.
func (*Web_Grpc) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Web_Grpc) GetMaxConcurrencyUnary() int32 {
	if x != nil {
		return x.MaxConcurrencyUnary
	}
	return 0
}

func (x *Web_Grpc) GetMaxConcurrencyStream() int32 {
	if x != nil {
		return x.MaxConcurrencyStream
	}
	return 0
}

func (x *Web_Grpc) GetMaxReceiveMessageSize() int32 {
	if x != nil {
		return x.MaxReceiveMessageSize
	}
	return 0
}

func (x *Web_Grpc) GetMaxSendMessageSize() int32 {
	if x != nil {
		return x.MaxSendMessageSize
	}
	return 0
}

func (x *Web_Grpc) GetTimeout() *duration.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Web_Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiFormatter   Web_Http_ApiFormatter `protobuf:"varint,1,opt,name=api_formatter,json=apiFormatter,proto3,enum=go.pkg.webserver.Web_Http_ApiFormatter" json:"api_formatter,omitempty"`
	MaxConcurrency int32                 `protobuf:"varint,2,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	// timeout 0 is not unlimited
	Timeout *duration.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *Web_Http) Reset() {
	*x = Web_Http{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Http) ProtoMessage() {}

func (x *Web_Http) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Http.ProtoReflect.Descriptor instead.
func (*Web_Http) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Web_Http) GetApiFormatter() Web_Http_ApiFormatter {
	if x != nil {
		return x.ApiFormatter
	}
	return Web_Http_api_noop
}

func (x *Web_Http) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *Web_Http) GetTimeout() *duration.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Web_Debug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableProfiling             bool     `protobuf:"varint,1,opt,name=enable_profiling,json=enableProfiling,proto3" json:"enable_profiling,omitempty"`
	DisablePrintInoutputMethods []string `protobuf:"bytes,2,rep,name=disable_print_inoutput_methods,json=disablePrintInoutputMethods,proto3" json:"disable_print_inoutput_methods,omitempty"`
}

func (x *Web_Debug) Reset() {
	*x = Web_Debug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Debug) ProtoMessage() {}

func (x *Web_Debug) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Debug.ProtoReflect.Descriptor instead.
func (*Web_Debug) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Web_Debug) GetEnableProfiling() bool {
	if x != nil {
		return x.EnableProfiling
	}
	return false
}

func (x *Web_Debug) GetDisablePrintInoutputMethods() []string {
	if x != nil {
		return x.DisablePrintInoutputMethods
	}
	return nil
}

type Web_Monitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prometheus *Web_Monitor_Prometheus `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
}

func (x *Web_Monitor) Reset() {
	*x = Web_Monitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Monitor) ProtoMessage() {}

func (x *Web_Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Monitor.ProtoReflect.Descriptor instead.
func (*Web_Monitor) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Web_Monitor) GetPrometheus() *Web_Monitor_Prometheus {
	if x != nil {
		return x.Prometheus
	}
	return nil
}

type Web_Monitor_Prometheus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnabledMetricTimerCost   bool `protobuf:"varint,1,opt,name=enabled_metric_timer_cost,json=enabledMetricTimerCost,proto3" json:"enabled_metric_timer_cost,omitempty"`
	EnabledMetricCodeMessage bool `protobuf:"varint,2,opt,name=enabled_metric_code_message,json=enabledMetricCodeMessage,proto3" json:"enabled_metric_code_message,omitempty"`
}

func (x *Web_Monitor_Prometheus) Reset() {
	*x = Web_Monitor_Prometheus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_webserver_webserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Web_Monitor_Prometheus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web_Monitor_Prometheus) ProtoMessage() {}

func (x *Web_Monitor_Prometheus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_webserver_webserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web_Monitor_Prometheus.ProtoReflect.Descriptor instead.
func (*Web_Monitor_Prometheus) Descriptor() ([]byte, []int) {
	return file_pkg_webserver_webserver_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Web_Monitor_Prometheus) GetEnabledMetricTimerCost() bool {
	if x != nil {
		return x.EnabledMetricTimerCost
	}
	return false
}

func (x *Web_Monitor_Prometheus) GetEnabledMetricCodeMessage() bool {
	if x != nil {
		return x.EnabledMetricCodeMessage
	}
	return false
}

var File_pkg_webserver_webserver_proto protoreflect.FileDescriptor

var file_pkg_webserver_webserver_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbb, 0x09, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x12, 0x3c, 0x0a, 0x0c, 0x62, 0x69, 0x6e,
	0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x0b, 0x62, 0x69, 0x6e, 0x64,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77,
	0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x12, 0x2e, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77,
	0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x48, 0x74, 0x74,
	0x70, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x31, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x12, 0x37, 0x0a, 0x07, 0x6d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f,
	0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57,
	0x65, 0x62, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x1a, 0x2d, 0x0a, 0x03, 0x4e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x1a, 0x91, 0x02, 0x0a, 0x04, 0x47, 0x72, 0x70, 0x63, 0x12, 0x32, 0x0a, 0x15, 0x6d,
	0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75,
	0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x6d, 0x61, 0x78, 0x43,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x34, 0x0a, 0x16, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x14, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x37, 0x0a, 0x18, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31,
	0x0a, 0x15, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x6d,
	0x61, 0x78, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x1a, 0x8e, 0x02, 0x0a, 0x04, 0x48, 0x74, 0x74, 0x70, 0x12,
	0x4c, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x48, 0x74,
	0x74, 0x70, 0x2e, 0x41, 0x70, 0x69, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x52,
	0x0c, 0x61, 0x70, 0x69, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a,
	0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x5a, 0x0a, 0x0c, 0x41,
	0x70, 0x69, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x08, 0x61,
	0x70, 0x69, 0x5f, 0x6e, 0x6f, 0x6f, 0x70, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x74, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x33, 0x30, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x30,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x5f, 0x76, 0x32, 0x30, 0x10, 0x03, 0x1a, 0x77, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x43, 0x0a, 0x1e, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x1b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x6e,
	0x74, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x1a, 0xdc, 0x01, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x48, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x62, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d,
	0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x1a, 0x86, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x65, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x19, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74,
	0x12, 0x3d, 0x0a, 0x1b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61,
	0x79, 0x64, 0x78, 0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x77, 0x65, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x77, 0x65, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_webserver_webserver_proto_rawDescOnce sync.Once
	file_pkg_webserver_webserver_proto_rawDescData = file_pkg_webserver_webserver_proto_rawDesc
)

func file_pkg_webserver_webserver_proto_rawDescGZIP() []byte {
	file_pkg_webserver_webserver_proto_rawDescOnce.Do(func() {
		file_pkg_webserver_webserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_webserver_webserver_proto_rawDescData)
	})
	return file_pkg_webserver_webserver_proto_rawDescData
}

var file_pkg_webserver_webserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_webserver_webserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_webserver_webserver_proto_goTypes = []interface{}{
	(Web_Http_ApiFormatter)(0),     // 0: go.pkg.webserver.Web.Http.ApiFormatter
	(*Web)(nil),                    // 1: go.pkg.webserver.Web
	(*Web_Net)(nil),                // 2: go.pkg.webserver.Web.Net
	(*Web_Grpc)(nil),               // 3: go.pkg.webserver.Web.Grpc
	(*Web_Http)(nil),               // 4: go.pkg.webserver.Web.Http
	(*Web_Debug)(nil),              // 5: go.pkg.webserver.Web.Debug
	(*Web_Monitor)(nil),            // 6: go.pkg.webserver.Web.Monitor
	(*Web_Monitor_Prometheus)(nil), // 7: go.pkg.webserver.Web.Monitor.Prometheus
	(*duration.Duration)(nil),      // 8: google.protobuf.Duration
}
var file_pkg_webserver_webserver_proto_depIdxs = []int32{
	2, // 0: go.pkg.webserver.Web.bind_address:type_name -> go.pkg.webserver.Web.Net
	3, // 1: go.pkg.webserver.Web.grpc:type_name -> go.pkg.webserver.Web.Grpc
	4, // 2: go.pkg.webserver.Web.http:type_name -> go.pkg.webserver.Web.Http
	5, // 3: go.pkg.webserver.Web.debug:type_name -> go.pkg.webserver.Web.Debug
	6, // 4: go.pkg.webserver.Web.monitor:type_name -> go.pkg.webserver.Web.Monitor
	8, // 5: go.pkg.webserver.Web.Grpc.timeout:type_name -> google.protobuf.Duration
	0, // 6: go.pkg.webserver.Web.Http.api_formatter:type_name -> go.pkg.webserver.Web.Http.ApiFormatter
	8, // 7: go.pkg.webserver.Web.Http.timeout:type_name -> google.protobuf.Duration
	7, // 8: go.pkg.webserver.Web.Monitor.prometheus:type_name -> go.pkg.webserver.Web.Monitor.Prometheus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_webserver_webserver_proto_init() }
func file_pkg_webserver_webserver_proto_init() {
	if File_pkg_webserver_webserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_webserver_webserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Net); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Grpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Http); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Debug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Monitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_webserver_webserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Web_Monitor_Prometheus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_webserver_webserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_webserver_webserver_proto_goTypes,
		DependencyIndexes: file_pkg_webserver_webserver_proto_depIdxs,
		EnumInfos:         file_pkg_webserver_webserver_proto_enumTypes,
		MessageInfos:      file_pkg_webserver_webserver_proto_msgTypes,
	}.Build()
	File_pkg_webserver_webserver_proto = out.File
	file_pkg_webserver_webserver_proto_rawDesc = nil
	file_pkg_webserver_webserver_proto_goTypes = nil
	file_pkg_webserver_webserver_proto_depIdxs = nil
}
