/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: gocv.swigcxx

#ifndef SWIG_gocv_WRAP_H_
#define SWIG_gocv_WRAP_H_

class Swig_memory;

#endif
