// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: pkg/fsnotify/fsnotify.proto

package fsnotify

import (
	_ "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fsnotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled   bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FilePaths []string `protobuf:"bytes,2,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
}

func (x *Fsnotify) Reset() {
	*x = Fsnotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_fsnotify_fsnotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fsnotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fsnotify) ProtoMessage() {}

func (x *Fsnotify) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fsnotify_fsnotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fsnotify.ProtoReflect.Descriptor instead.
func (*Fsnotify) Descriptor() ([]byte, []int) {
	return file_pkg_fsnotify_fsnotify_proto_rawDescGZIP(), []int{0}
}

func (x *Fsnotify) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Fsnotify) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

var File_pkg_fsnotify_fsnotify_proto protoreflect.FileDescriptor

var file_pkg_fsnotify_fsnotify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x66,
	0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67,
	0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x66, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43,
	0x0a, 0x08, 0x46, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x61, 0x79, 0x64, 0x78, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x66, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x3b, 0x66, 0x73, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_fsnotify_fsnotify_proto_rawDescOnce sync.Once
	file_pkg_fsnotify_fsnotify_proto_rawDescData = file_pkg_fsnotify_fsnotify_proto_rawDesc
)

func file_pkg_fsnotify_fsnotify_proto_rawDescGZIP() []byte {
	file_pkg_fsnotify_fsnotify_proto_rawDescOnce.Do(func() {
		file_pkg_fsnotify_fsnotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_fsnotify_fsnotify_proto_rawDescData)
	})
	return file_pkg_fsnotify_fsnotify_proto_rawDescData
}

var file_pkg_fsnotify_fsnotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_fsnotify_fsnotify_proto_goTypes = []interface{}{
	(*Fsnotify)(nil), // 0: go.pkg.fsnotify.Fsnotify
}
var file_pkg_fsnotify_fsnotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_fsnotify_fsnotify_proto_init() }
func file_pkg_fsnotify_fsnotify_proto_init() {
	if File_pkg_fsnotify_fsnotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_fsnotify_fsnotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fsnotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_fsnotify_fsnotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_fsnotify_fsnotify_proto_goTypes,
		DependencyIndexes: file_pkg_fsnotify_fsnotify_proto_depIdxs,
		MessageInfos:      file_pkg_fsnotify_fsnotify_proto_msgTypes,
	}.Build()
	File_pkg_fsnotify_fsnotify_proto = out.File
	file_pkg_fsnotify_fsnotify_proto_rawDesc = nil
	file_pkg_fsnotify_fsnotify_proto_goTypes = nil
	file_pkg_fsnotify_fsnotify_proto_depIdxs = nil
}
