// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: opentelemetry.proto

package opentelemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtelTraceExporterType int32

const (
	OtelTraceExporterType_trace_none   OtelTraceExporterType = 0
	OtelTraceExporterType_trace_stdout OtelTraceExporterType = 1
	OtelTraceExporterType_trace_otlp   OtelTraceExporterType = 2
	OtelTraceExporterType_trace_jaeger OtelTraceExporterType = 3
	OtelTraceExporterType_trace_zipkin OtelTraceExporterType = 4
)

// Enum value maps for OtelTraceExporterType.
var (
	OtelTraceExporterType_name = map[int32]string{
		0: "trace_none",
		1: "trace_stdout",
		2: "trace_otlp",
		3: "trace_jaeger",
		4: "trace_zipkin",
	}
	OtelTraceExporterType_value = map[string]int32{
		"trace_none":   0,
		"trace_stdout": 1,
		"trace_otlp":   2,
		"trace_jaeger": 3,
		"trace_zipkin": 4,
	}
)

func (x OtelTraceExporterType) Enum() *OtelTraceExporterType {
	p := new(OtelTraceExporterType)
	*p = x
	return p
}

func (x OtelTraceExporterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtelTraceExporterType) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_enumTypes[0].Descriptor()
}

func (OtelTraceExporterType) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_enumTypes[0]
}

func (x OtelTraceExporterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtelTraceExporterType.Descriptor instead.
func (OtelTraceExporterType) EnumDescriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{0}
}

type OtelMetricExporterType int32

const (
	OtelMetricExporterType_metric_none       OtelMetricExporterType = 0
	OtelMetricExporterType_metric_stdout     OtelMetricExporterType = 1
	OtelMetricExporterType_metric_otlp       OtelMetricExporterType = 2
	OtelMetricExporterType_metric_prometheus OtelMetricExporterType = 3
)

// Enum value maps for OtelMetricExporterType.
var (
	OtelMetricExporterType_name = map[int32]string{
		0: "metric_none",
		1: "metric_stdout",
		2: "metric_otlp",
		3: "metric_prometheus",
	}
	OtelMetricExporterType_value = map[string]int32{
		"metric_none":       0,
		"metric_stdout":     1,
		"metric_otlp":       2,
		"metric_prometheus": 3,
	}
)

func (x OtelMetricExporterType) Enum() *OtelMetricExporterType {
	p := new(OtelMetricExporterType)
	*p = x
	return p
}

func (x OtelMetricExporterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtelMetricExporterType) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_enumTypes[1].Descriptor()
}

func (OtelMetricExporterType) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_enumTypes[1]
}

func (x OtelMetricExporterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtelMetricExporterType.Descriptor instead.
func (OtelMetricExporterType) EnumDescriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{1}
}

type OtelLogExporterType int32

const (
	OtelLogExporterType_log_none OtelLogExporterType = 0
	OtelLogExporterType_log_otlp OtelLogExporterType = 1
)

// Enum value maps for OtelLogExporterType.
var (
	OtelLogExporterType_name = map[int32]string{
		0: "log_none",
		1: "log_otlp",
	}
	OtelLogExporterType_value = map[string]int32{
		"log_none": 0,
		"log_otlp": 1,
	}
)

func (x OtelLogExporterType) Enum() *OtelLogExporterType {
	p := new(OtelLogExporterType)
	*p = x
	return p
}

func (x OtelLogExporterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtelLogExporterType) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_enumTypes[2].Descriptor()
}

func (OtelLogExporterType) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_enumTypes[2]
}

func (x OtelLogExporterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtelLogExporterType.Descriptor instead.
func (OtelLogExporterType) EnumDescriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{2}
}

// OpenTelemetry 统一监控配置（去掉 Monitor 包装层）
type OpenTelemetry struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Enabled                bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MetricCollectDuration  *durationpb.Duration   `protobuf:"bytes,2,opt,name=metric_collect_duration,json=metricCollectDuration,proto3" json:"metric_collect_duration,omitempty"`
	OtelTraceExporterType  OtelTraceExporterType  `protobuf:"varint,3,opt,name=otel_trace_exporter_type,json=otelTraceExporterType,proto3,enum=go.pkg.opentelemetry.OtelTraceExporterType" json:"otel_trace_exporter_type,omitempty"`
	OtelMetricExporterType OtelMetricExporterType `protobuf:"varint,4,opt,name=otel_metric_exporter_type,json=otelMetricExporterType,proto3,enum=go.pkg.opentelemetry.OtelMetricExporterType" json:"otel_metric_exporter_type,omitempty"`
	OtelLogExporterType    OtelLogExporterType    `protobuf:"varint,5,opt,name=otel_log_exporter_type,json=otelLogExporterType,proto3,enum=go.pkg.opentelemetry.OtelLogExporterType" json:"otel_log_exporter_type,omitempty"`
	OtelMetricExporter     *OtelMetricExporter    `protobuf:"bytes,6,opt,name=otel_metric_exporter,json=otelMetricExporter,proto3" json:"otel_metric_exporter,omitempty"`
	OtelTraceExporter      *OtelTraceExporter     `protobuf:"bytes,7,opt,name=otel_trace_exporter,json=otelTraceExporter,proto3" json:"otel_trace_exporter,omitempty"`
	Resource               *Resource              `protobuf:"bytes,10,opt,name=resource,proto3" json:"resource,omitempty"`
	// 从旧 Monitor.Prometheus 迁移的配置
	EnabledMetricTimerCost   bool `protobuf:"varint,20,opt,name=enabled_metric_timer_cost,json=enabledMetricTimerCost,proto3" json:"enabled_metric_timer_cost,omitempty"`
	EnabledMetricCodeMessage bool `protobuf:"varint,21,opt,name=enabled_metric_code_message,json=enabledMetricCodeMessage,proto3" json:"enabled_metric_code_message,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *OpenTelemetry) Reset() {
	*x = OpenTelemetry{}
	mi := &file_opentelemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTelemetry) ProtoMessage() {}

func (x *OpenTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTelemetry.ProtoReflect.Descriptor instead.
func (*OpenTelemetry) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{0}
}

func (x *OpenTelemetry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OpenTelemetry) GetMetricCollectDuration() *durationpb.Duration {
	if x != nil {
		return x.MetricCollectDuration
	}
	return nil
}

func (x *OpenTelemetry) GetOtelTraceExporterType() OtelTraceExporterType {
	if x != nil {
		return x.OtelTraceExporterType
	}
	return OtelTraceExporterType_trace_none
}

func (x *OpenTelemetry) GetOtelMetricExporterType() OtelMetricExporterType {
	if x != nil {
		return x.OtelMetricExporterType
	}
	return OtelMetricExporterType_metric_none
}

func (x *OpenTelemetry) GetOtelLogExporterType() OtelLogExporterType {
	if x != nil {
		return x.OtelLogExporterType
	}
	return OtelLogExporterType_log_none
}

func (x *OpenTelemetry) GetOtelMetricExporter() *OtelMetricExporter {
	if x != nil {
		return x.OtelMetricExporter
	}
	return nil
}

func (x *OpenTelemetry) GetOtelTraceExporter() *OtelTraceExporter {
	if x != nil {
		return x.OtelTraceExporter
	}
	return nil
}

func (x *OpenTelemetry) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *OpenTelemetry) GetEnabledMetricTimerCost() bool {
	if x != nil {
		return x.EnabledMetricTimerCost
	}
	return false
}

func (x *OpenTelemetry) GetEnabledMetricCodeMessage() bool {
	if x != nil {
		return x.EnabledMetricCodeMessage
	}
	return false
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // default use process name
	Attrs         map[string]string      `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_opentelemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Resource) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type OtelMetricExporter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prometheus    *Prometheus            `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	Stdout        *Stdout                `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Otlp          *OTLP                  `protobuf:"bytes,3,opt,name=otlp,proto3" json:"otlp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtelMetricExporter) Reset() {
	*x = OtelMetricExporter{}
	mi := &file_opentelemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtelMetricExporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtelMetricExporter) ProtoMessage() {}

func (x *OtelMetricExporter) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtelMetricExporter.ProtoReflect.Descriptor instead.
func (*OtelMetricExporter) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{2}
}

func (x *OtelMetricExporter) GetPrometheus() *Prometheus {
	if x != nil {
		return x.Prometheus
	}
	return nil
}

func (x *OtelMetricExporter) GetStdout() *Stdout {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *OtelMetricExporter) GetOtlp() *OTLP {
	if x != nil {
		return x.Otlp
	}
	return nil
}

type OtelTraceExporter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jaeger        *Jaeger                `protobuf:"bytes,1,opt,name=jaeger,proto3" json:"jaeger,omitempty"`
	Stdout        *Stdout                `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Otlp          *OTLP                  `protobuf:"bytes,3,opt,name=otlp,proto3" json:"otlp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtelTraceExporter) Reset() {
	*x = OtelTraceExporter{}
	mi := &file_opentelemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtelTraceExporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtelTraceExporter) ProtoMessage() {}

func (x *OtelTraceExporter) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtelTraceExporter.ProtoReflect.Descriptor instead.
func (*OtelTraceExporter) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{3}
}

func (x *OtelTraceExporter) GetJaeger() *Jaeger {
	if x != nil {
		return x.Jaeger
	}
	return nil
}

func (x *OtelTraceExporter) GetStdout() *Stdout {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *OtelTraceExporter) GetOtlp() *OTLP {
	if x != nil {
		return x.Otlp
	}
	return nil
}

type Prometheus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prometheus) Reset() {
	*x = Prometheus{}
	mi := &file_opentelemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prometheus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prometheus) ProtoMessage() {}

func (x *Prometheus) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prometheus.ProtoReflect.Descriptor instead.
func (*Prometheus) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Prometheus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Jaeger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jaeger) Reset() {
	*x = Jaeger{}
	mi := &file_opentelemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jaeger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jaeger) ProtoMessage() {}

func (x *Jaeger) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jaeger.ProtoReflect.Descriptor instead.
func (*Jaeger) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{5}
}

func (x *Jaeger) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Stdout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrettyPrint   bool                   `protobuf:"varint,1,opt,name=pretty_print,json=prettyPrint,proto3" json:"pretty_print,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stdout) Reset() {
	*x = Stdout{}
	mi := &file_opentelemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdout) ProtoMessage() {}

func (x *Stdout) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdout.ProtoReflect.Descriptor instead.
func (*Stdout) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{6}
}

func (x *Stdout) GetPrettyPrint() bool {
	if x != nil {
		return x.PrettyPrint
	}
	return false
}

// OTLP exporter configuration for Tencent Cloud Prometheus or other OTLP-compatible backends
type OTLP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint URL (e.g., "prometheus.tencentcloudapi.com:4317" for gRPC)
	// For Tencent Cloud Prometheus, use the Remote Write address from console
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Authentication token (e.g., Tencent Cloud Prometheus Token)
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Protocol: "http" or "grpc" (default: "http")
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Use insecure connection (default: false)
	Insecure bool `protobuf:"varint,4,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// Custom headers for authentication
	Headers map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// URL path for HTTP protocol (default: "/v1/metrics")
	UrlPath       string `protobuf:"bytes,6,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTLP) Reset() {
	*x = OTLP{}
	mi := &file_opentelemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTLP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTLP) ProtoMessage() {}

func (x *OTLP) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTLP.ProtoReflect.Descriptor instead.
func (*OTLP) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_rawDescGZIP(), []int{7}
}

func (x *OTLP) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OTLP) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OTLP) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OTLP) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *OTLP) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *OTLP) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

var File_opentelemetry_proto protoreflect.FileDescriptor

const file_opentelemetry_proto_rawDesc = "" +
	"\n" +
	"\x13opentelemetry.proto\x12\x14go.pkg.opentelemetry\x1a\x1egoogle/protobuf/duration.proto\"\x96\x06\n" +
	"\rOpenTelemetry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12Q\n" +
	"\x17metric_collect_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15metricCollectDuration\x12d\n" +
	"\x18otel_trace_exporter_type\x18\x03 \x01(\x0e2+.go.pkg.opentelemetry.OtelTraceExporterTypeR\x15otelTraceExporterType\x12g\n" +
	"\x19otel_metric_exporter_type\x18\x04 \x01(\x0e2,.go.pkg.opentelemetry.OtelMetricExporterTypeR\x16otelMetricExporterType\x12^\n" +
	"\x16otel_log_exporter_type\x18\x05 \x01(\x0e2).go.pkg.opentelemetry.OtelLogExporterTypeR\x13otelLogExporterType\x12Z\n" +
	"\x14otel_metric_exporter\x18\x06 \x01(\v2(.go.pkg.opentelemetry.OtelMetricExporterR\x12otelMetricExporter\x12W\n" +
	"\x13otel_trace_exporter\x18\a \x01(\v2'.go.pkg.opentelemetry.OtelTraceExporterR\x11otelTraceExporter\x12:\n" +
	"\bresource\x18\n" +
	" \x01(\v2\x1e.go.pkg.opentelemetry.ResourceR\bresource\x129\n" +
	"\x19enabled_metric_timer_cost\x18\x14 \x01(\bR\x16enabledMetricTimerCost\x12=\n" +
	"\x1benabled_metric_code_message\x18\x15 \x01(\bR\x18enabledMetricCodeMessage\"\xa8\x01\n" +
	"\bResource\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12?\n" +
	"\x05attrs\x18\x02 \x03(\v2).go.pkg.opentelemetry.Resource.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x12OtelMetricExporter\x12@\n" +
	"\n" +
	"prometheus\x18\x01 \x01(\v2 .go.pkg.opentelemetry.PrometheusR\n" +
	"prometheus\x124\n" +
	"\x06stdout\x18\x02 \x01(\v2\x1c.go.pkg.opentelemetry.StdoutR\x06stdout\x12.\n" +
	"\x04otlp\x18\x03 \x01(\v2\x1a.go.pkg.opentelemetry.OTLPR\x04otlp\"\xaf\x01\n" +
	"\x11OtelTraceExporter\x124\n" +
	"\x06jaeger\x18\x01 \x01(\v2\x1c.go.pkg.opentelemetry.JaegerR\x06jaeger\x124\n" +
	"\x06stdout\x18\x02 \x01(\v2\x1c.go.pkg.opentelemetry.StdoutR\x06stdout\x12.\n" +
	"\x04otlp\x18\x03 \x01(\v2\x1a.go.pkg.opentelemetry.OTLPR\x04otlp\"\x1e\n" +
	"\n" +
	"Prometheus\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1a\n" +
	"\x06Jaeger\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"+\n" +
	"\x06Stdout\x12!\n" +
	"\fpretty_print\x18\x01 \x01(\bR\vprettyPrint\"\x8a\x02\n" +
	"\x04OTLP\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1a\n" +
	"\binsecure\x18\x04 \x01(\bR\binsecure\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.go.pkg.opentelemetry.OTLP.HeadersEntryR\aheaders\x12\x19\n" +
	"\burl_path\x18\x06 \x01(\tR\aurlPath\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*m\n" +
	"\x15OtelTraceExporterType\x12\x0e\n" +
	"\n" +
	"trace_none\x10\x00\x12\x10\n" +
	"\ftrace_stdout\x10\x01\x12\x0e\n" +
	"\n" +
	"trace_otlp\x10\x02\x12\x10\n" +
	"\ftrace_jaeger\x10\x03\x12\x10\n" +
	"\ftrace_zipkin\x10\x04*d\n" +
	"\x16OtelMetricExporterType\x12\x0f\n" +
	"\vmetric_none\x10\x00\x12\x11\n" +
	"\rmetric_stdout\x10\x01\x12\x0f\n" +
	"\vmetric_otlp\x10\x02\x12\x15\n" +
	"\x11metric_prometheus\x10\x03*1\n" +
	"\x13OtelLogExporterType\x12\f\n" +
	"\blog_none\x10\x00\x12\f\n" +
	"\blog_otlp\x10\x01B:Z8github.com/kaydxh/golang/pkg/opentelemetry;opentelemetryb\x06proto3"

var (
	file_opentelemetry_proto_rawDescOnce sync.Once
	file_opentelemetry_proto_rawDescData []byte
)

func file_opentelemetry_proto_rawDescGZIP() []byte {
	file_opentelemetry_proto_rawDescOnce.Do(func() {
		file_opentelemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_rawDesc), len(file_opentelemetry_proto_rawDesc)))
	})
	return file_opentelemetry_proto_rawDescData
}

var file_opentelemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_opentelemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_opentelemetry_proto_goTypes = []any{
	(OtelTraceExporterType)(0),  // 0: go.pkg.opentelemetry.OtelTraceExporterType
	(OtelMetricExporterType)(0), // 1: go.pkg.opentelemetry.OtelMetricExporterType
	(OtelLogExporterType)(0),    // 2: go.pkg.opentelemetry.OtelLogExporterType
	(*OpenTelemetry)(nil),       // 3: go.pkg.opentelemetry.OpenTelemetry
	(*Resource)(nil),            // 4: go.pkg.opentelemetry.Resource
	(*OtelMetricExporter)(nil),  // 5: go.pkg.opentelemetry.OtelMetricExporter
	(*OtelTraceExporter)(nil),   // 6: go.pkg.opentelemetry.OtelTraceExporter
	(*Prometheus)(nil),          // 7: go.pkg.opentelemetry.Prometheus
	(*Jaeger)(nil),              // 8: go.pkg.opentelemetry.Jaeger
	(*Stdout)(nil),              // 9: go.pkg.opentelemetry.Stdout
	(*OTLP)(nil),                // 10: go.pkg.opentelemetry.OTLP
	nil,                         // 11: go.pkg.opentelemetry.Resource.AttrsEntry
	nil,                         // 12: go.pkg.opentelemetry.OTLP.HeadersEntry
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_opentelemetry_proto_depIdxs = []int32{
	13, // 0: go.pkg.opentelemetry.OpenTelemetry.metric_collect_duration:type_name -> google.protobuf.Duration
	0,  // 1: go.pkg.opentelemetry.OpenTelemetry.otel_trace_exporter_type:type_name -> go.pkg.opentelemetry.OtelTraceExporterType
	1,  // 2: go.pkg.opentelemetry.OpenTelemetry.otel_metric_exporter_type:type_name -> go.pkg.opentelemetry.OtelMetricExporterType
	2,  // 3: go.pkg.opentelemetry.OpenTelemetry.otel_log_exporter_type:type_name -> go.pkg.opentelemetry.OtelLogExporterType
	5,  // 4: go.pkg.opentelemetry.OpenTelemetry.otel_metric_exporter:type_name -> go.pkg.opentelemetry.OtelMetricExporter
	6,  // 5: go.pkg.opentelemetry.OpenTelemetry.otel_trace_exporter:type_name -> go.pkg.opentelemetry.OtelTraceExporter
	4,  // 6: go.pkg.opentelemetry.OpenTelemetry.resource:type_name -> go.pkg.opentelemetry.Resource
	11, // 7: go.pkg.opentelemetry.Resource.attrs:type_name -> go.pkg.opentelemetry.Resource.AttrsEntry
	7,  // 8: go.pkg.opentelemetry.OtelMetricExporter.prometheus:type_name -> go.pkg.opentelemetry.Prometheus
	9,  // 9: go.pkg.opentelemetry.OtelMetricExporter.stdout:type_name -> go.pkg.opentelemetry.Stdout
	10, // 10: go.pkg.opentelemetry.OtelMetricExporter.otlp:type_name -> go.pkg.opentelemetry.OTLP
	8,  // 11: go.pkg.opentelemetry.OtelTraceExporter.jaeger:type_name -> go.pkg.opentelemetry.Jaeger
	9,  // 12: go.pkg.opentelemetry.OtelTraceExporter.stdout:type_name -> go.pkg.opentelemetry.Stdout
	10, // 13: go.pkg.opentelemetry.OtelTraceExporter.otlp:type_name -> go.pkg.opentelemetry.OTLP
	12, // 14: go.pkg.opentelemetry.OTLP.headers:type_name -> go.pkg.opentelemetry.OTLP.HeadersEntry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_opentelemetry_proto_init() }
func file_opentelemetry_proto_init() {
	if File_opentelemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_rawDesc), len(file_opentelemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opentelemetry_proto_goTypes,
		DependencyIndexes: file_opentelemetry_proto_depIdxs,
		EnumInfos:         file_opentelemetry_proto_enumTypes,
		MessageInfos:      file_opentelemetry_proto_msgTypes,
	}.Build()
	File_opentelemetry_proto = out.File
	file_opentelemetry_proto_goTypes = nil
	file_opentelemetry_proto_depIdxs = nil
}
